# Generated by Django 5.1.1 on 2024-09-23 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="game",
            field=models.ManyToManyField(
                related_name="teams", through="app.TeamToGame", to="app.game"
            ),
        ),
        migrations.AlterField(
            model_name="teamtogame",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games",
                to="app.game",
            ),
        ),
    ]
