# Generated by Django 5.1.1 on 2024-09-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_team_game_alter_teamtogame_game"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="game",
        ),
        migrations.AddField(
            model_name="game",
            name="score_away",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="score_home",
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name="TeamToGame",
        ),
    ]
