# Generated by Django 5.1.1 on 2024-09-23 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_team_game_game_score_away_game_score_home_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="date_time",
            field=models.DateTimeField(null=True),
        ),
    ]
