# Generated by Django 5.1.1 on 2024-10-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_game_date_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="teams",
            field=models.ManyToManyField(related_name="tournaments", to="app.team"),
        ),
    ]
